
// Kuaishou Report System - Cloudflare Worker
// Single File Implementation

export default {
    async fetch(request, env, ctx) {
        const url = new URL(request.url);

        // 1. Serve the Frontend UI
        if (url.pathname === '/' && request.method === 'GET') {
            return new Response(htmlContent, {
                headers: {
                    'content-type': 'text/html;charset=UTF-8',
                },
            });
        }

        // 2. API Proxy Endpoint
        if (url.pathname === '/api/report' && request.method === 'POST') {
            try {
                const payload = await request.json();
                let internalUserId = payload.targetId;

                // Check if the input is a numeric Kuaishou ID (userDefineId) vs internal ID
                const isNumericId = /^\d+$/.test(payload.targetId);

                if (isNumericId) {
                    // Need to resolve numeric Kuaishou ID to internal user_id via search
                    const searchUrl = 'https://www.kuaishou.com/graphql';
                    const searchHeaders = {
                        'Host': 'www.kuaishou.com',
                        'Origin': 'https://www.kuaishou.com',
                        'Referer': 'https://www.kuaishou.com/search/author?searchKey=' + encodeURIComponent(payload.targetId),
                        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                        'Content-Type': 'application/json',
                        'Accept': '*/*',
                        'Cookie': payload.cookies || '',
                        'kpn': 'KUAISHOU_VISION'
                    };

                    const searchQuery = {
                        operationName: "visionSearchUser",
                        variables: {
                            keyword: payload.targetId,
                            pcursor: "",
                            searchSessionId: ""
                        },
                        query: "query visionSearchUser($keyword: String, $pcursor: String, $searchSessionId: String) { visionSearchUser(keyword: $keyword, pcursor: $pcursor, searchSessionId: $searchSessionId) { result users { user_id user_name headurl user_text } pcursor searchSessionId } }"
                    };

                    const searchResp = await fetch(searchUrl, {
                        method: 'POST',
                        headers: searchHeaders,
                        body: JSON.stringify(searchQuery)
                    });

                    const searchData = await searchResp.json();

                    if (searchData?.data?.visionSearchUser?.users?.length > 0) {
                        internalUserId = searchData.data.visionSearchUser.users[0].user_id;
                    } else {
                        return new Response(JSON.stringify({
                            status: 404,
                            body: JSON.stringify({ result: 0, error_msg: '未找到该快手号对应的用户，请检查ID是否正确' })
                        }), {
                            headers: { 'content-type': 'application/json', 'access-control-allow-origin': '*' }
                        });
                    }
                }

                // Target Kuaishou API
                const targetUrl = 'https://www.kuaishou.com/rest/v/report/submit';

                // Construct headers exactly as requested, but using cookies/tokens from the client payload
                const headers = {
                    'Host': 'www.kuaishou.com',
                    'Origin': 'https://www.kuaishou.com',
                    'Referer': `https://www.kuaishou.com/profile/${internalUserId}`,
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                    'Connection': 'keep-alive',
                    'Cookie': payload.cookies || '', // Client must provide valid cookies (did, didv, etc.) or we mock some
                    'kww': payload.kww, // The crucial token generated by client
                    'kpn': 'KUAISHOU_VISION'
                };

                // Update the data payload with resolved internal ID
                const reportData = {
                    ...payload.data,
                    reportedUserId: internalUserId,
                    targetId: internalUserId
                };

                const response = await fetch(targetUrl, {
                    method: 'POST',
                    headers: headers,
                    body: JSON.stringify(reportData)
                });

                const respText = await response.text();

                return new Response(JSON.stringify({
                    status: response.status,
                    headers: Object.fromEntries(response.headers),
                    body: respText,
                    resolvedUserId: internalUserId // Include resolved ID for debugging
                }), {
                    headers: {
                        'content-type': 'application/json',
                        'access-control-allow-origin': '*'
                    }
                });

            } catch (e) {
                return new Response(JSON.stringify({ error: e.message }), { status: 500 });
            }
        }

        // 3. User Profile Proxy Endpoint
        if (url.pathname === '/api/profile' && request.method === 'POST') {
            try {
                const payload = await request.json();
                let internalUserId = payload.targetId;

                // Check if the input is a numeric Kuaishou ID (userDefineId) vs internal ID (contains 'x')
                // Internal IDs look like: 3xn9cwxxrfh4ydw
                // Kuaishou IDs (userDefineId) are numeric: 4501316236
                const isNumericId = /^\d+$/.test(payload.targetId);

                if (isNumericId) {
                    // Need to resolve numeric Kuaishou ID to internal user_id via search
                    const searchUrl = 'https://www.kuaishou.com/graphql';
                    const searchHeaders = {
                        'Host': 'www.kuaishou.com',
                        'Origin': 'https://www.kuaishou.com',
                        'Referer': 'https://www.kuaishou.com/search/author?searchKey=' + encodeURIComponent(payload.targetId),
                        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                        'Content-Type': 'application/json',
                        'Accept': '*/*',
                        'Cookie': payload.cookies || '',
                        'kpn': 'KUAISHOU_VISION'
                    };

                    const searchQuery = {
                        operationName: "visionSearchUser",
                        variables: {
                            keyword: payload.targetId,
                            pcursor: "",
                            searchSessionId: ""
                        },
                        query: "query visionSearchUser($keyword: String, $pcursor: String, $searchSessionId: String) { visionSearchUser(keyword: $keyword, pcursor: $pcursor, searchSessionId: $searchSessionId) { result users { user_id user_name headurl user_text } pcursor searchSessionId } }"
                    };

                    const searchResp = await fetch(searchUrl, {
                        method: 'POST',
                        headers: searchHeaders,
                        body: JSON.stringify(searchQuery)
                    });

                    const searchData = await searchResp.json();

                    if (searchData?.data?.visionSearchUser?.users?.length > 0) {
                        // Find exact match by userDefineId or take first result
                        internalUserId = searchData.data.visionSearchUser.users[0].user_id;
                    } else {
                        return new Response(JSON.stringify({
                            status: 404,
                            body: JSON.stringify({ result: 0, error_msg: '未找到该快手号对应的用户，请检查ID是否正确' })
                        }), {
                            headers: { 'content-type': 'application/json' }
                        });
                    }
                }

                // Now fetch profile with the internal user_id
                const targetUrl = 'https://www.kuaishou.com/rest/v/profile/user';

                const headers = {
                    'Host': 'www.kuaishou.com',
                    'Origin': 'https://www.kuaishou.com',
                    'Referer': `https://www.kuaishou.com/profile/${internalUserId}`,
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                    'Connection': 'keep-alive',
                    'Cookie': payload.cookies || '',
                    'kww': payload.kww,
                    'kpn': 'KUAISHOU_VISION'
                };

                const response = await fetch(targetUrl, {
                    method: 'POST',
                    headers: headers,
                    body: JSON.stringify({ user_id: internalUserId })
                });

                const respText = await response.text();

                return new Response(JSON.stringify({
                    status: response.status,
                    body: respText,
                    resolvedUserId: internalUserId // Include resolved ID for debugging
                }), {
                    headers: { 'content-type': 'application/json' }
                });

            } catch (e) {
                return new Response(JSON.stringify({ error: e.message }), { status: 500 });
            }
        }

        return new Response('Not Found', { status: 404 });
    }
};

// ==========================================
// FRONTEND HTML CONTENT
// ==========================================
const htmlContent = `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KS-REPORT | 核心执法系统</title>
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&family=Inter:wght@400;600;800&display=swap" rel="stylesheet">
    <style>
        :root {
            --primary: #FF3506; /* Kuaishou Red */
            --primary-dim: rgba(255, 53, 6, 0.3);
            --accent: #00F260;
            --bg-dark: #050507;
            --glass: rgba(255, 255, 255, 0.03);
            --glass-border: rgba(255, 255, 255, 0.08);
            --text-main: #ffffff;
            --text-muted: #666666;
            --card-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
        }

        * { box-sizing: border-box; }

        body {
            margin: 0;
            padding: 0;
            background-color: var(--bg-dark);
            color: var(--text-main);
            font-family: 'Inter', system-ui, sans-serif;
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            overflow: hidden;
            background-image: 
                radial-gradient(circle at 20% 20%, rgba(255, 53, 6, 0.08) 0%, transparent 40%),
                radial-gradient(circle at 80% 80%, rgba(0, 50, 255, 0.05) 0%, transparent 40%);
        }

        /* Scanlines */
        body::after {
            content: "";
            position: absolute;
            top: 0; left: 0; width: 100%; height: 100%;
            background: linear-gradient(rgba(18, 16, 16, 0) 50%, rgba(0, 0, 0, 0.25) 50%), linear-gradient(90deg, rgba(255, 0, 0, 0.06), rgba(0, 255, 0, 0.02), rgba(0, 0, 255, 0.06));
            background-size: 100% 2px, 3px 100%;
            pointer-events: none;
            z-index: 10;
        }

        .container {
            position: relative;
            z-index: 2;
            width: 1100px;
            max-width: 95%;
            display: grid;
            grid-template-columns: 1.2fr 0.8fr;
            gap: 24px;
            height: 85vh;
        }

        .card {
            background: rgba(15, 15, 20, 0.6);
            backdrop-filter: blur(24px);
            -webkit-backdrop-filter: blur(24px);
            border: 1px solid var(--glass-border);
            border-radius: 24px;
            padding: 40px;
            box-shadow: var(--card-shadow);
            display: flex;
            flex-direction: column;
            overflow-y: auto;
            position: relative;
            transition: border-color 0.3s;
        }

        .card:hover {
            border-color: rgba(255, 53, 6, 0.3);
        }

        /* Scrollbar */
        ::-webkit-scrollbar { width: 6px; }
        ::-webkit-scrollbar-track { background: transparent; }
        ::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.1); border-radius: 3px; }
        ::-webkit-scrollbar-thumb:hover { background: rgba(255,255,255,0.2); }

        h1 {
            font-family: 'JetBrains Mono', monospace;
            font-size: 28px;
            margin: 0 0 8px 0;
            background: linear-gradient(90deg, #fff, #aaa);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            letter-spacing: -1px;
        }

        h2 {
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 2px;
            color: var(--primary);
            margin: 0 0 30px 0;
            opacity: 0.8;
            font-family: 'JetBrains Mono', monospace;
        }

        .input-section {
            display: flex;
            flex-direction: column;
            gap: 20px;
            margin-bottom: 20px;
        }

        label {
            display: flex;
            justify-content: space-between;
            font-size: 12px;
            color: var(--text-muted);
            margin-bottom: 8px;
            font-weight: 600;
        }

        label span.tip {
            color: var(--primary);
            cursor: pointer;
            opacity: 0.7;
        }
        label span.tip:hover { opacity: 1; text-decoration: underline; }

        input, textarea {
            width: 100%;
            background: rgba(0, 0, 0, 0.4);
            border: 1px solid var(--glass-border);
            border-radius: 12px;
            padding: 16px;
            color: #fff;
            font-family: 'JetBrains Mono', monospace;
            font-size: 13px;
            transition: all 0.3s ease;
        }

        input:focus, textarea:focus {
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 20px rgba(255, 53, 6, 0.15);
            background: rgba(0, 0, 0, 0.7);
        }

        textarea {
            resize: vertical;
            min-height: 120px;
            line-height: 1.6;
        }
        
        /* Cookie Input Specifics */
        .cookie-box textarea {
            min-height: 80px;
            color: #aaffaa;
            font-size: 11px;
        }

        .btn-primary {
            background: linear-gradient(135deg, var(--primary), #a31600);
            color: white;
            border: none;
            padding: 18px;
            border-radius: 12px;
            font-weight: 700;
            font-size: 14px;
            cursor: pointer;
            letter-spacing: 1px;
            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
            text-transform: uppercase;
            margin-top: auto;
            position: relative;
            overflow: hidden;
            box-shadow: 0 10px 30px rgba(255, 53, 6, 0.3);
        }

        .btn-primary::after {
            content: '';
            position: absolute;
            top: 0; left: -100%;
            width: 100%; height: 100%;
            background: linear-gradient(90deg, transparent, rgba(255,255,255,0.2), transparent);
            transition: 0.5s;
        }

        .btn-primary:hover::after {
            left: 100%;
        }

        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 15px 40px rgba(255, 53, 6, 0.5);
        }

        .btn-primary:active { transform: scale(0.98); }

        .btn-primary.loading {
            background: #333;
            cursor: wait;
            opacity: 0.8;
            box-shadow: none;
        }

        /* Right Panel: Terminal */
        .terminal-header {
            display: flex;
            gap: 8px;
            margin-bottom: 15px;
        }
        .dot { width: 10px; height: 10px; border-radius: 50%; }
        .red { background: #ff5f56; }
        .yellow { background: #ffbd2e; }
        .green { background: #27c93f; }

        .terminal-window {
            flex: 1;
            font-family: 'JetBrains Mono', monospace;
            font-size: 12px;
            color: #00f260;
            overflow-y: auto;
            position: relative;
        }

        .log-entry {
            margin-bottom: 8px;
            display: flex;
            opacity: 0;
            animation: fadeIn 0.3s forwards;
        }
        
        .log-entry.error { color: #ff3506; }
        .log-entry.warn { color: #ffbd2e; }
        .log-entry.info { color: #5dade2; }

        .timestamp {
            opacity: 0.5;
            margin-right: 12px;
            min-width: 70px;
        }

        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(5px); }
            to { opacity: 1; transform: translateY(0); }
        }

        .stats-row {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 15px;
            margin-bottom: 25px;
        }
        
        .stat-box {
            background: rgba(255,255,255,0.03);
            border-radius: 12px;
            padding: 15px;
            text-align: center;
        }
        
        .stat-val { font-size: 24px; font-weight: 800; color: #fff; }
        .stat-label { font-size: 10px; color: var(--text-muted); text-transform: uppercase; margin-top: 5px; }

        /* Profile Preview Card */
        .preview-card {
            background: linear-gradient(145deg, rgba(255,255,255,0.05), rgba(255,255,255,0.02));
            border: 1px solid var(--glass-border);
            border-radius: 12px;
            padding: 15px;
            margin-top: 15px;
            display: none; /* Hidden by default */
            animation: fadeIn 0.4s ease-out;
            backdrop-filter: blur(10px);
        }
        .preview-content { display: flex; gap: 15px; align-items: flex-start; }
        .preview-avatar { 
            width: 60px; height: 60px; border-radius: 50%; 
            border: 2px solid var(--primary); 
            object-fit: cover;
            box-shadow: 0 4px 12px rgba(0,0,0,0.3);
        }
        .preview-info { flex: 1; }
        .preview-name { 
            font-size: 16px; font-weight: 700; color: #fff; margin-bottom: 4px;
            display: flex; align-items: center; gap: 5px;
        }
        .preview-id { font-size: 12px; color: var(--text-muted); font-family: 'JetBrains Mono', monospace; }
        .preview-bio {
            font-size: 12px; color: #aaa; margin-top: 8px; line-height: 1.4;
            background: rgba(0,0,0,0.2); padding: 8px; border-radius: 6px;
        }
        .preview-stats {
            display: flex; gap: 15px; margin-top: 10px; border-top: 1px solid rgba(255,255,255,0.05); padding-top: 8px;
        }
        .p-stat { font-size: 11px; color: #888; }
        .p-stat b { color: #ddd; margin-left: 2px; }
        
        .check-btn {
            background: rgba(255,255,255,0.1); border: 1px solid rgba(255,255,255,0.1);
            color: #ccc; padding: 0 10px; border-radius: 4px; cursor: pointer;
            font-size: 12px; margin-left: 10px; transition: all 0.2s;
        }
        .check-btn:hover { background: rgba(255,255,255,0.2); color: #fff; }

    </style>
</head>
<body>

<div class="container">
    <!-- Config Panel -->
    <div class="card">
        <h1>STRIKE // 核心打击</h1>
        <h2>举报执法控制台</h2>
        
        <div class="input-section">
            <div>
                <label>目标用户 UID <span class="tip" onclick="pasteClipboard('targetId')">[粘贴]</span> <button class="check-btn" onclick="checkTarget()">🔍 预览目标</button></label>
                <input type="text" id="targetId" value="3xn9cwxxrfh4ydw" placeholder="输入快手用户ID...">
                
                <div id="previewCard" class="preview-card">
                    <!-- Populated by JS -->
                    <div style="text-align: center; color: #666; font-size: 12px;">点击“预览目标”加载信息</div>
                </div>
            </div>

            <div class="cookie-box">
                <label>安全令牌 (Cookie) <span class="tip" onclick="pasteClipboard('cookieInput')">[自动填充]</span></label>
                <textarea id="cookieInput" placeholder="必须！在此粘贴您的 'did=...; didv=...' 字符串。举报需要有效的 Cookie。"></textarea>
            </div>

            <div>
                <label>违规详情</label>
                <textarea id="reportDetail"></textarea>
            </div>
        </div>

        <div class="input-section" style="margin-bottom: 20px;">
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px;">
                <div>
                    <label>执行次数 (循环)</label>
                    <input type="number" id="loopCount" value="10" min="1" placeholder="例如: 10">
                </div>
                <div>
                    <label>间隔时间 (秒) <span class="tip">[建议 2-5s]</span></label>
                    <input type="number" id="loopInterval" value="3" min="1" placeholder="例如: 3">
                </div>
            </div>
        </div>

        <div style="display: flex; gap: 10px;">
            <button class="btn-primary" id="startBtn" onclick="startReport()" style="flex: 1;">
                单次打击 // 立即执行
            </button>
            <button class="btn-primary" id="autoBtn" onclick="startAutoReport()" style="flex: 1; background: linear-gradient(135deg, #FF9800, #F44336);">
                自动打击 // 循环模式
            </button>
        </div>
    </div>

    <!-- Terminal Panel -->
    <div class="card" style="background: rgba(0,0,0,0.85);">
        <div class="terminal-header">
            <div class="dot red"></div>
            <div class="dot yellow"></div>
            <div class="dot green"></div>
        </div>
        
        <div class="stats-row">
            <div class="stat-box">
                <div class="stat-val" id="reqCount">0</div>
                <div class="stat-label">请求数</div>
            </div>
            <div class="stat-box">
                <div class="stat-val" style="color:var(--primary)" id="errCount">0</div>
                <div class="stat-label">错误数</div>
            </div>
        </div>

        <div class="terminal-window" id="console">
            <div class="log-entry"><span class="timestamp">[系统]</span> 系统已初始化。就绪。</div>
            <div class="log-entry info"><span class="timestamp">[提示]</span> 请提供有效的 Cookie 以避免 109 错误。</div>
        </div>
    </div>
</div>

<script>
    // PRESETS
    const DEFAULT_REASON = "致审核专员：\\n请务必人工阅读！该账号极其狡猾，表面看是在分享游戏配置，实则是利用黑产专用术语（黑话）规避系统检测 ，进行外挂推广和诈骗引流。\\n\\n1️⃣ 视觉画面实锤：非法篡改客户端数据\\n视频中的亮度已突破正常曝光极限，且无阴影，属于典型的“透视/除草”修改。\\n\\n2️⃣ 话术解码：黑产专用语\\n所谓“配置文件”即外挂脚本，“V1/V2”代表外挂暴力程度。\\n\\n严肃诉求：\\n该账号行为涉嫌触犯《刑法》帮信罪，请平台永久封禁！若推诿不处理，我将向网信办举报平台失职！";
    document.getElementById('reportDetail').value = DEFAULT_REASON;

    // PRESET COOKIE (User Provided)
    const DEFAULT_COOKIE = "";
    
    // Set default cookie directly
    document.getElementById('cookieInput').value = DEFAULT_COOKIE;

    // UTILS
    function log(msg, type = '') {
        const consoleEl = document.getElementById('console');
        const now = new Date().toLocaleTimeString('en-US', {hour12: false});
        const entry = document.createElement('div');
        entry.className = \`log-entry \${type}\`;
        entry.innerHTML = \`<span class="timestamp">[\${now}]</span> \${msg}\`;
        consoleEl.appendChild(entry);
        consoleEl.scrollTop = consoleEl.scrollHeight;
    }

    async function pasteClipboard(id) {
        try {
            const text = await navigator.clipboard.readText();
            document.getElementById(id).value = text;
            log('剪贴板内容已粘贴。', 'info');
        } catch (e) {
            log('无法访问剪贴板。', 'warn');
        }
    }

    let reqs = 0;
    let errors = 0;

    async function checkTarget() {
        const targetId = document.getElementById('targetId').value.trim();
        const cookieStr = document.getElementById('cookieInput').value.trim();
        const card = document.getElementById('previewCard');

        if (!targetId) { log("请输入目标 ID", "warn"); return; }
        
        log("🔍 正在获取目标信息...", "info");
        card.style.display = 'block';
        card.innerHTML = '<div style="text-align:center; padding:20px;">⌛ 加载中...</div>';

        try {
            const response = await fetch('/api/profile', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    targetId: targetId,
                    cookies: cookieStr,
                    kww: "PnGU+9+Y8008S+nH0U+0mjPf8fP08f+98f+nLlwnrIP9+Sw/ZFGfzY+eGlGf+f+e4SGfbYP0QfGnLFwBLU80mYGAq9PAW9+erl8fcF8nL7G0Y0+eGM+0+0wn+YPfHIGfr98eY0+0WhG/cI8eHlP0Ll+ecFweWlPf+YPnGIG/LI8nQf+eq7PBPh808f8/Zl+0DI+/pS80S0PeGA80QjG/zS+I=="
                })
            });
            
            const result = await response.json();
            if (result.status !== 200) throw new Error("API 错误: " + result.status);
            
            let body;
            try { body = JSON.parse(result.body); } catch(e) { body = result.body; }

            if (body.result !== 1) throw new Error(body.error_msg || "获取失败/Cookie无效");

            const p = body.userProfile.profile;
            const s = body.userProfile.ownerCount;

            card.innerHTML = \`
                <div class="preview-content">
                    <img src="\${p.headurl}" class="preview-avatar">
                    <div class="preview-info">
                        <div class="preview-name">\${p.user_name}</div>
                        <div class="preview-id">ID: \${p.user_id}</div>
                        <div class="preview-bio">\${p.user_text || '无简介'}</div>
                    </div>
                </div>
                <div class="preview-stats">
                    <div class="p-stat">粉丝 <b>\${s.fan}</b></div>
                    <div class="p-stat">获赞 <b>\${s.like}</b></div>
                    <div class="p-stat">关注 <b>\${s.follow}</b></div>
                </div>
            \`;
            log("✅ 目标信息获取成功: " + p.user_name, "info");

        } catch (e) {
            log("❌ " + e.message, "error");
            card.innerHTML = '<div style="text-align:center; color:#ff3506; padding:10px;">❌ 获取失败: ' + e.message + '</div>';
        }
    }

    // AUTO REPORT LOGIC
    let isAutoRunning = false;

    async function startAutoReport() {
        if (isAutoRunning) {
            isAutoRunning = false;
            log("🛑 用户中止了自动打击任务。", "warn");
            return;
        }

        const count = parseInt(document.getElementById('loopCount').value) || 10;
        const interval = parseInt(document.getElementById('loopInterval').value) || 3;
        const btn = document.getElementById('autoBtn');
        const startBtn = document.getElementById('startBtn');

        isAutoRunning = true;
        btn.innerHTML = '🛑 停止自动打击';
        btn.classList.add('loading');
        startBtn.disabled = true;

        log("=========================================");
        log("🚀 启动自动打击模式", "info");
        log("🎯 目标次数: " + count + " 次 | ⏱️ 间隔: " + interval + " 秒", "info");
        log("=========================================");

        for (let i = 1; i <= count; i++) {
            if (!isAutoRunning) break;

            log("\\n[循环 " + i + "/" + count + "] 正在执行...");
            await startReport(true); // true = silent mode (no button reset)

            if (i < count && isAutoRunning) {
                log("⏳ 等待 " + interval + " 秒冷却...", "info");
                await new Promise(r => setTimeout(r, interval * 1000));
            }
        }

        isAutoRunning = false;
        btn.innerHTML = '自动打击 // 循环模式';
        btn.classList.remove('loading');
        startBtn.disabled = false;
        log("\\n✅ 自动打击序列已结束。", "info");
    }

    async function startReport(isAuto = false) {
        const btn = document.getElementById('startBtn');
        const targetId = document.getElementById('targetId').value.trim();
        const cookieStr = document.getElementById('cookieInput').value.trim();
        const detail = document.getElementById('reportDetail').value;

        if (!targetId || !cookieStr) { 
            log("中止：缺少必要信息。目标 ID 和 Cookie 为必填项。", "error");
            errors++; updateStats();
            return; 
        }

        // Save cookie for convenience
        localStorage.setItem('ks_cookie', cookieStr);

        if (!isAuto) {
            btn.classList.add('loading');
            btn.innerHTML = '⚡ 执行中...';
            log("-----------------------------------------");
            log("开始执行目标：" + targetId);
        }
        
        // log("正在验证凭据..."); // Reduce spam in auto mode

        try {
            // Hardcoded fingerprint/token logic would go here
            // For now, we trust the user provided KWW kww logic is embedded/or we rely on cookies
            // The previous "HARDCODED_KWW" is likely expired too, but the cookie is the main gate.
            
            // Construct Payload
            const payload = {
                targetId: targetId,
                kww: "PnGU+9+Y8008S+nH0U+0mjPf8fP08f+98f+nLlwnrIP9+Sw/ZFGfzY+eGlGf+f+e4SGfbYP0QfGnLFwBLU80mYGAq9PAW9+erl8fcF8nL7G0Y0+eGM+0+0wn+YPfHIGfr98eY0+0WhG/cI8eHlP0Ll+ecFweWlPf+YPnGIG/LI8nQf+eq7PBPh808f8/Zl+0DI+/pS80S0PeGA80QjG/zS+I==", // Keep or update if possible
                cookies: cookieStr,
                data: {
                    "extraPhotoId": "",
                    "page": "PROFILE",
                    "reportDetail": detail,
                    "reportItem": 203,
                    "reportType": 2,
                    "reportedUserId": targetId,
                    "targetId": targetId
                }
            };

            // log("连接已建立。正在发送数据...", "info");

            const response = await fetch('/api/report', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });

            reqs++;
            const result = await response.json();
            
            if (result.status === 200) {
                 // Parse inner body
                 let inner;
                 try { inner = JSON.parse(result.body); } catch(e) { inner = result.body; }
                 
                 if (inner.result === 1) {
                     log("✅ 成功：举报已送达。", "info");
                     if (!isAuto) btn.innerHTML = '✅ 任务完成';
                 } else if (inner.result === 109) {
                     log("❌ 失败：认证被拒绝 (Cookie 无效)", "error");
                     errors++;
                     if (!isAuto) btn.innerHTML = '❌ 认证失败';
                     if (isAuto) isAutoRunning = false; // Stop auto on auth fail
                 } else {
                     log("⚠️ 状态：" + (JSON.stringify(inner) || "未知"));
                     if (!isAuto) btn.innerHTML = '⚠️ 已完成';
                 }
            } else {
                 log("❌ 上游错误：" + (result.status || "未知"), "error");
                 if (result.body) {
                     try {
                        const bodyObj = JSON.parse(result.body);
                        const msg = bodyObj.error_msg || bodyObj.errorMsg || bodyObj.errMsg || "未知错误";
                        log("📝 原因：" + msg, "warn");
                     } catch(e) {
                         log("📝 详细：" + result.body.substring(0, 100), "warn");
                     }
                 }
                 if (result.error) {
                     log("Worker 错误：" + result.error, "error");
                 }
                 errors++;
                 if (!isAuto) btn.innerHTML = '❌ 失败';
            }
            
        } catch (err) {
            log("💥 严重错误：" + err.message, "error");
            errors++;
            if (!isAuto) btn.innerHTML = '❌ 系统错误';
        } finally {
            updateStats();
            if (!isAuto) {
                setTimeout(() => { 
                    if(!btn.innerHTML.includes('执行中')) {
                        btn.classList.remove('loading'); 
                        if(btn.innerHTML.includes('❌')) {
                             setTimeout(() => btn.innerHTML = '重试程序', 2000);
                        } else {
                             setTimeout(() => btn.innerHTML = '单次打击 // 立即执行', 2000);
                        }
                    }
                }, 500);
            }
        }
    }

    function updateStats() {
        document.getElementById('reqCount').innerText = reqs;
        document.getElementById('errCount').innerText = errors;
    }
</script>
</body>
</html>
`;
